name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: '54.89.110.248'

    - name: Deploy to EC2
      run: |
        ssh -i /home/ec2-user/devops-lifecycle/test-keypair.pem ec2-user@54.89.110.248 'cd /home/ec2-user/devops-lifecycle && git pull && pm2 restart app'
